name: "Testing/Linting/Fuzzing"

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
      - name: Run linter
        run: python3 run-checks.py --lint
      - name: Run typechecker
        run: python3 run-checks.py --type-check
      - name: Run unit tests
        run: python3 run-checks.py --unit-test
      - name: Run integration tests
        run: python3 run-checks.py --doc-test
      - name: Run fuzzer
        run: python3 run-checks.py --fuzz
